from os import PathLike
from pathlib import Path

import pyarrow

__all__ = ["Dir", "Tree", "scan"]

def scan(path: str | PathLike, threads: int | None = None) -> Tree: ...

class Tree:
    @property
    def root(self) -> Dir: ...
    def find(self, path: str | PathLike) -> Dir | None: ...
    def largest_files(self, n: int = 100) -> list[tuple[Path, int]]: ...
    def to_arrow(self) -> pyarrow.Table: ...

class Dir:
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> Path: ...
    @property
    def size(self) -> int: ...
    @property
    def own(self) -> int: ...
    @property
    def error(self) -> str | None: ...
    @property
    def partial(self) -> bool: ...
    @property
    def other_device(self) -> bool: ...
    def children(self) -> list[Dir]: ...
