from os import PathLike
from pathlib import Path
from typing import Optional, Union

import pyarrow

__all__ = ["Dir", "Tree", "scan"]

def scan(path: Union[str, PathLike], threads: Optional[int] = None) -> Tree: ...

class Tree:
    @property
    def root(self) -> Dir: ...
    def find(self, path: Union[str, PathLike]) -> Optional[Dir]: ...
    def largest_files(self, n: int = 100) -> list[tuple[Path, int]]: ...
    def to_arrow(self) -> pyarrow.Table: ...

class Dir:
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> Path: ...
    @property
    def size(self) -> int: ...
    @property
    def own(self) -> int: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def partial(self) -> bool: ...
    @property
    def other_device(self) -> bool: ...
    def children(self) -> list[Dir]: ...
